apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-be
  labels:
    app: interview-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-be
  template:
    metadata:
      labels:
        app: interview-be
    spec:
      containers:
        - name: interview-be
          image: 6lackcoder/interview-be:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          
           # Liveness and Readiness Probes
          livenessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5

          # Resource Requests and Limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

  